version: '2'
services:
  bot:
    image: "crypto-bot:0.6-slim"
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - TZ=Europe/Berlin
    env_file: .env
    volumes:
      - ./Trades/Portfolio:/usr/src/trades
      - ./Trades/Completed:/usr/src/complete_trades
      - ./Conf:/usr/src/configs:ro
    restart: always
